services:
  mysql:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: nox_admin
      MYSQL_USER: nox_app
      MYSQL_PASSWORD: nox_local_password
      MYSQL_ROOT_PASSWORD: nox_local_root_password
      TZ: America/Panama
    ports:
      - "3306:3306"
    volumes:
      - nox_mysql_data:/var/lib/mysql
      - ./db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pnox_local_root_password"]
      interval: 5s
      timeout: 5s
      retries: 20

  app:
    build: .
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: 3000
      APP_ORIGIN: http://localhost:3000
      JWT_SECRET: cambie-este-secreto-antes-de-usar-en-produccion-123456789
      COOKIE_SECURE: "false"
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: nox_admin
      DB_USER: nox_app
      DB_PASSWORD: nox_local_password
    ports:
      - "3000:3000"

volumes:
  nox_mysql_data:
